# Add 'javascript` label to any change in the src folder
javascript:
  - src/**/*
  - scripts/**/*
  - public/**/*
  - .tool-versions
  - docs/**/*
  - CLAUDE.md

documentation:
  - docs/**/*
  - CLAUDE.md
  - README.md
  - AGENTS.md

configuration:
  - next.config.ts
  - next-env.d.ts
  - postcss.config.js
  - biome.json
  - jest.config.ts
  - tsconfig.json
  - vercel.json
  - .browserslistrc
  - stylelint.config.mjs
  - knip.json

# Add `dependencies` label to any changes to package.json or pnpm-lock.yaml
dependencies:
  - .tool-versions
  - package.json
  - pnpm-lock.yaml
  - pnpm-workspace.yaml
