#!/usr/bin/env bash
set -euo pipefail

# preToolUse (Write|StrReplace): deny hand-edits to generated Contentful types.
# src/contentful/types/ is produced by `pnpm types:contentful`.

source "$(dirname "$0")/_lib.sh"
hook_input

file="$(tool_file_path)"

case "$file" in
  */src/contentful/types/* | src/contentful/types/*) ;;
  *) exit 0 ;;
esac

reason="Blocked: src/contentful/types/ is generated by \`pnpm types:contentful\` and must not be hand-edited. If a CMS content type changed, the user regenerates the types, then you update the consumers. See docs/handbook/contentful.md."

deny_tool "$reason"
exit 0
