name: CI
on:
  pull_request:
    branches:
      - staging
jobs:
  ci:
    name: Lint/Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
        name: Checkout code
        with:
          fetch-depth: 0
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          package_json_file: package.json
      - name: Read Node.js version from .tool-versions
        id: get_node_version
        run: |
          echo "$(awk '/nodejs/ {print $2}' .tool-versions)"
          echo "node_version=$(awk '/nodejs/ {print $2}' .tool-versions)" >> $GITHUB_OUTPUT
        shell: bash
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.get_node_version.outputs.node_version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run TSC
        run: pnpm tsc:ci
      - name: Run ESLint
        run: pnpm lint:ci
      - name: Run Stylelint
        run: pnpm lint:css
      - name: Run Jest
        run: pnpm test:ci
