name: CI
on:
  pull_request:
    branches:
      - staging
jobs:
  ci:
    name: Lint/Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
        name: Checkout code
        with:
          fetch-depth: 0
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9.0.6
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run TSC
        run: sudo yarn tsc:ci
      - name: Run ESLint
        run: sudo yarn lint:ci
      - name: Run Stylelint
        run: sudo yarn lint:css
      - name: Run Jest
        run: sudo yarn test:ci
